<script lang="ts">
    import {
        compareSnapshots,
        parseCsvSnapshot,
        parseJsonSnapshot,
        type ComparisonResult,
        type ValueSnapshot
    } from "$lib/utils/value-compare";

    let baselineName = "";
    let targetName = "";

    let baselineValues: ValueSnapshot[] = [];
    let targetValues: ValueSnapshot[] = [];

    let result: ComparisonResult | null = null;
    let errorText = "";

    function parseFileContent(fileName: string, content: string): ValueSnapshot[] {
        const lower = fileName.toLowerCase();
        if (lower.endsWith(".json")) return parseJsonSnapshot(content);
        if (lower.endsWith(".csv")) return parseCsvSnapshot(content);

        const jsonValues = parseJsonSnapshot(content);
        if (jsonValues.length > 0) return jsonValues;

        return parseCsvSnapshot(content);
    }

    async function handleFileSelect(event: Event, role: "baseline" | "target") {
        const input = event.target as HTMLInputElement;
        const file = input.files?.[0];

        if (!file) return;

        const content = await file.text();
        const values = parseFileContent(file.name, content);

        if (values.length === 0) {
            errorText =
                "Could not parse export file. Use JSON/CSV exports generated by this application.";
            return;
        }

        errorText = "";

        if (role === "baseline") {
            baselineName = file.name;
            baselineValues = values;
        } else {
            targetName = file.name;
            targetValues = values;
        }

        if (baselineValues.length > 0 && targetValues.length > 0) {
            result = compareSnapshots(baselineValues, targetValues);
        }
    }

    function pretty(value: string | number | boolean | null) {
        if (value === null) return "null";
        if (typeof value === "boolean") return value ? "true" : "false";
        return String(value);
    }

    function pct(confidence: number) {
        return `${Math.round(confidence * 100)}%`;
    }
</script>

<svelte:head>
    <title>Compare</title>
</svelte:head>

<section class="flex flex-col h-full gap-4">
    <h1>Compare Exports</h1>

    <p class="text-neutral-300 text-sm md:text-base">
        Load two exported value files to detect key additions, removals, and mapping changes across versions.
    </p>

    <div class="compare-grid">
        <label class="compare-card">
            <span class="card-title">Baseline Export</span>
            <input type="file" accept=".json,.csv" on:change={(event) => handleFileSelect(event, "baseline")} />
            <span class="text-neutral-400 text-sm">{baselineName || "No file selected"}</span>
            <span class="text-neutral-400 text-sm">Keys: {baselineValues.length}</span>
        </label>

        <label class="compare-card">
            <span class="card-title">Target Export</span>
            <input type="file" accept=".json,.csv" on:change={(event) => handleFileSelect(event, "target")} />
            <span class="text-neutral-400 text-sm">{targetName || "No file selected"}</span>
            <span class="text-neutral-400 text-sm">Keys: {targetValues.length}</span>
        </label>
    </div>

    {#if errorText}
        <p class="text-red-400">{errorText}</p>
    {/if}

    {#if result}
        <section class="summary-grid">
            <article class="summary-card">
                <h2>Added In Target</h2>
                <p>{result.onlyInB.length}</p>
            </article>
            <article class="summary-card">
                <h2>Removed From Target</h2>
                <p>{result.onlyInA.length}</p>
            </article>
            <article class="summary-card">
                <h2>Changed</h2>
                <p>{result.changed.length}</p>
            </article>
            <article class="summary-card">
                <h2>Unchanged</h2>
                <p>{result.unchanged.length}</p>
            </article>
        </section>

        <section class="terminal compare-list">
            <h2 class="panel-title">Changed Keys</h2>
            {#if result.changed.length === 0}
                <p class="text-neutral-400">No changed keys found.</p>
            {:else}
                <ul class="change-list">
                    {#each result.changed as item}
                        <li class="change-item">
                            <div class="change-header">
                                <strong>{item.key}</strong>
                                <span class="packet-prefix">[{item.changes.join(", ")}]</span>
                            </div>
                            <div class="change-row">
                                <span class="text-neutral-400">Baseline:</span>
                                <span>{pretty(item.before.value)}</span>
                                <span>{item.before.path}</span>
                                <span>{item.before.sourcePacket}</span>
                                <span>{pct(item.before.confidence)}</span>
                            </div>
                            <div class="change-row">
                                <span class="text-neutral-400">Target:</span>
                                <span>{pretty(item.after.value)}</span>
                                <span>{item.after.path}</span>
                                <span>{item.after.sourcePacket}</span>
                                <span>{pct(item.after.confidence)}</span>
                            </div>
                        </li>
                    {/each}
                </ul>
            {/if}
        </section>

        <div class="compare-grid">
            <section class="terminal compare-list">
                <h2 class="panel-title">Added Keys</h2>
                {#if result.onlyInB.length === 0}
                    <p class="text-neutral-400">None</p>
                {:else}
                    <ul>
                        {#each result.onlyInB as item}
                            <li>{item.key} = {pretty(item.value)} <span class="packet-prefix">[{item.path}]</span></li>
                        {/each}
                    </ul>
                {/if}
            </section>

            <section class="terminal compare-list">
                <h2 class="panel-title">Removed Keys</h2>
                {#if result.onlyInA.length === 0}
                    <p class="text-neutral-400">None</p>
                {:else}
                    <ul>
                        {#each result.onlyInA as item}
                            <li>{item.key} = {pretty(item.value)} <span class="packet-prefix">[{item.path}]</span></li>
                        {/each}
                    </ul>
                {/if}
            </section>
        </div>
    {/if}
</section>

<style lang="postcss">
    .compare-grid {
        @apply grid gap-4 md:grid-cols-2;
    }

    .compare-card {
        @apply flex flex-col gap-2 rounded-xl border border-neutral-700 bg-neutral-900/70 p-4;
    }

    .card-title {
        @apply text-lg font-quicksand;
    }

    .summary-grid {
        @apply grid gap-3 grid-cols-2 md:grid-cols-4;
    }

    .summary-card {
        @apply rounded-xl border border-neutral-700 bg-neutral-800/70 p-4 text-center;
    }

    .summary-card h2 {
        @apply text-base;
    }

    .summary-card p {
        @apply text-2xl mt-1;
    }

    .compare-list {
        @apply flex flex-col gap-3;
    }

    .panel-title {
        @apply text-xl;
    }

    .change-list {
        @apply flex flex-col gap-4;
    }

    .change-item {
        @apply border-b border-neutral-700 pb-3;
    }

    .change-header {
        @apply flex items-center gap-3;
    }

    .change-row {
        @apply grid gap-2 text-sm md:text-base mt-1;
        grid-template-columns: minmax(6rem, 8rem) minmax(4rem, 8rem) 1fr minmax(8rem, 12rem) minmax(4rem, 6rem);
    }
</style>
